# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_instructions: >
    Keep the summary concise: max 3 bullet points, no tables, no code blocks.
  poem: false
  review_status: true
  collapse_walkthrough: true
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  in_progress_fortune: false
  enable_prompt_for_ai_agents: true

  auto_review:
    enabled: true
    drafts: false

  tools:
    github-checks:
      timeout_ms: 900000

  # Keep review signal high by ignoring vendored/generated artifacts.
  path_filters:
    - "!**/.cache/**"
    - "!**/.deps/**"
    - "!**/.libs/**"
    - "!**/autom4te.cache/**"
    - "!**/*.o"
    - "!**/*.lo"
    - "!**/*.la"
    - "!**/vgcore.*"
    - "!compile_commands.json"
    - "!config.h"
    - "!config.h.in"
    - "!external/**"
    - "!clboss-*.tar.gz"

  path_instructions:
    - path: "**/*.cpp"
      instructions: >
        Prefer small, targeted changes; keep behavior stable unless the PR is explicitly a refactor.
        Be conservative about concurrency and lifetime: check RAII, exception-safety, and ownership.
        Avoid suggesting style changes that contradict `.clang-format` / `.editorconfig`.
    - path: "**/*.hpp"
      instructions: >
        Prioritize API/lifetime clarity (ownership, threading expectations, exception guarantees).
    - path: "Ev/**"
      instructions: >
        Pay special attention to coroutine semantics (final suspend, cancellation/cleanup ordering),
        and ensure changes are safe under `make check` and under valgrind.
    - path: "Boss/**"
      instructions: >
        Consider CLN RPC interactions and invariants: error handling paths, logging, and restart safety.
        If behavior changes, suggest a focused test update/addition under `tests/`.
    - path: "tests/**"
      instructions: >
        Keep tests deterministic; avoid timing-based flakes; prefer minimal repros for bugs/regressions.

chat:
  auto_reply: true
